  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  server:
    build: .
    command: MessageServerAPI/cmd/apiserver/apiserver
    ports:
      - 9000:9000



