version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database-data:/var/lib/postgresql/data_2/
      - ./dbscript.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    restart: unless-stopped
    command: MessageServerAPI/cmd/apiserver/apiserver
    ports:
      - 9000:9000
    expose:
      - 9000
      - 5432
    depends_on:
      - db
volumes:
  database-data:



